name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx create project
        run: |
          sphinx-quickstart --sep -p "algorithms-implementation" -a "Ignacy Polak" -v "0.1" -r "0.1" -l en --ext-autodoc --ext-githubpages docs/ 
          echo -ne "import os\nimport sys\nsys.path.insert(0, os.path.abspath('../../src'))" >> docs/source/conf.py
      - name: Sphinx generate docs
        run: |
          sphinx-apidoc -o docs/source/ src/
      - name: Sphinx build
        run: |
          sphinx-build --builder html docs/source/ docs/build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
